import test from 'node:test';import assert from 'node:assert/strict';
import {createMatch,applyBall,nextInnings,isBatting,overs,battingResult,bowlingResult,newLeague,finishRound,schedule} from '../engine.js';import {PLAYERS,SEASONS} from '../data.js';
const make=(opts={})=>createMatch({xi:PLAYERS.slice(0,11),opponent:'Hornsey',limit:12,...opts});const ball=(m,runs=0,wicket=false)=>applyBall(m,{runs,wicket,label:'Test ball'});
test('career register includes every extracted row, bowling-only player, and key source totals',()=>{assert.equal(PLAYERS.length,173);assert.equal(new Set(PLAYERS.map(p=>p.name)).size,173);assert.equal(PLAYERS.find(p=>p.name==='Pete Croaker').wickets,288);assert.equal(PLAYERS.find(p=>p.name==='Sean Fegan').runs,1653);assert.ok(PLAYERS.find(p=>p.name==='Matt Holt'));for(const p of PLAYERS){assert.ok(p.bat>=0&&p.bat<=100);assert.ok(p.bowl>=0&&p.bowl<=100)}});
test('strike changes for odd runs and ends of overs; individual scores reconcile',()=>{const m=make();ball(m,1);assert.equal(m.innings[0].striker,1);ball(m,4);for(let i=0;i<4;i++)ball(m);assert.equal(m.innings[0].striker,0);assert.equal(m.innings[0].runs,5);assert.equal(m.innings[0].batting.reduce((s,b)=>s+b.runs,0),5);assert.equal(overs(m.innings[0].balls),'1.0')});
test('ten wickets ends an innings without selecting a twelfth batter',()=>{const m=make();for(let i=0;i<10;i++)ball(m,0,true);assert.equal(m.stage,'break');assert.equal(m.innings[0].wickets,10);assert.ok(m.innings[0].striker<11);assert.equal(ball(m,4),false)});
test('successful chase ends immediately, with a full boundary credited',()=>{const m=make({batFirst:false});for(let i=0;i<12;i++)ball(m,1);assert.equal(m.stage,'break');nextInnings(m);assert.ok(isBatting(m));for(let i=0;i<4;i++)ball(m,4);assert.equal(m.stage,'done');assert.equal(m.winner,'fours');assert.equal(m.innings[1].balls,4);assert.equal(m.innings[1].runs,16);assert.equal(ball(m,4),false)});
test('defending a score and a tie both resolve correctly',()=>{for(const tied of [false,true]){const m=make();for(let i=0;i<12;i++)ball(m,1);nextInnings(m);for(let i=0;i<12;i++)ball(m,tied?1:0);assert.equal(m.winner,tied?'tie':'fours')}});
test('bowling card records legal deliveries, conceded runs and wickets',()=>{const m=make({batFirst:false});ball(m,4);ball(m,0,true);assert.deepEqual(m.innings[0].bowling[m.bowler.name],{balls:2,runs:4,wickets:1})});
test('timing rewards controlled shots and mistimed lofting risks a wicket',()=>{assert.equal(battingResult({error:0,style:'loft'}).runs,6);assert.equal(battingResult({error:0,style:'drive'}).runs,4);assert.equal(battingResult({error:-.5,style:'loft',rng:()=>0}).wicket,true);assert.equal(battingResult({error:0,style:'defend'}).runs,1);assert.ok(bowlingResult({error:0,rating:95,rng:()=>0}).wicket)});
test('each historical league schedules every opponent once with at most one game per club per round',()=>{for(const s of SEASONS){const l=newLeague(s);const pairs=l.rounds.flat().map(g=>[...g].sort().join('|'));const n=s.teams.length+1;assert.equal(pairs.length,n*(n-1)/2);assert.equal(new Set(pairs).size,pairs.length);for(const round of l.rounds){const names=round.flat();assert.equal(new Set(names).size,names.length)}assert.equal(l.rounds.flat().filter(g=>g.includes('The Mighty Fours')).length,s.teams.length)}});
test('full campaign advances byes, awards points and cannot double count completion',()=>{const l=newLeague(SEASONS[1]);while(!l.complete)finishRound(l,'fours',()=>.3);for(const row of l.table)assert.equal(row.played,10);const us=l.table.find(t=>t.name==='The Mighty Fours');assert.equal(us.won,10);assert.equal(us.points,20);const old=JSON.stringify(l);finishRound(l,'fours');assert.equal(JSON.stringify(l),old)});
test('100 complete matches preserve innings invariants and terminate',()=>{for(let k=0;k<100;k++){const m=make({batFirst:k%2===0});let guard=0;while(m.stage!=='done'&&guard++<30){if(m.stage==='break'){nextInnings(m);continue}const result=isBatting(m)?battingResult({error:Math.random()-.4}):bowlingResult({error:Math.random()-.4});applyBall(m,result)}assert.equal(m.stage,'done');for(const i of m.innings){assert.ok(i.wickets<=10);assert.ok(i.balls<=12);assert.equal(i.runs,i.batting.reduce((s,b)=>s+b.runs,0));assert.equal(i.balls,i.batting.reduce((s,b)=>s+b.balls,0))}}});
test('source profiles distinguish spin from seam and explicitly mark unknown styles',()=>{
 for(const name of ['Chris Evans','Matt Dyke','Nick Friend'])assert.equal(PLAYERS.find(p=>p.name===name).bowlingType,'spin');
 for(const name of ['Pete Croaker','Brett Booth','Gaurav Patil'])assert.equal(PLAYERS.find(p=>p.name===name).bowlingType,'seam');
 assert.equal(PLAYERS.find(p=>p.name==='Matt Holt').bowlingVerified,false);
});
test('bowling movement interacts with chosen line and spin has distinct outcomes',()=>{
 const towards=bowlingResult({error:0,movement:'left',line:'off',rating:70,rng:()=>.26});
 const away=bowlingResult({error:0,movement:'right',line:'off',rating:70,rng:()=>.26});
 assert.equal(towards.wicket,true);assert.equal(away.wicket,false);
 assert.match(bowlingResult({error:0,movement:'right',bowlingType:'spin',rng:()=>0}).label,/Turned/);
 assert.match(bowlingResult({error:0,movement:'left',bowlingType:'seam',rng:()=>0}).label,/Swung/);
});
